'use strict';

module.exports = [
  '@generative-music/piece-a-viable-system',
  '@generative-music/piece-aisatsana',
  '@generative-music/piece-apoapsis',
  '@generative-music/piece-awash',
  '@generative-music/piece-buttafingers',
  '@generative-music/piece-day-dream',
  '@generative-music/piece-didgeridoobeats',
  '@generative-music/piece-drones',
  '@generative-music/piece-drones-2',
  '@generative-music/piece-eno-machine',
  '@generative-music/piece-enough',
  '@generative-music/piece-expand-collapse',
  '@generative-music/piece-homage',
  '@generative-music/piece-impact',
  '@generative-music/piece-lemniscate',
  '@generative-music/piece-little-bells',
  '@generative-music/piece-meditation',
  '@generative-music/piece-moment',
  '@generative-music/piece-neuroplasticity',
  '@generative-music/piece-observable-streams',
  '@generative-music/piece-otherness',
  '@generative-music/piece-peace',
  '@generative-music/piece-pinwheels',
  '@generative-music/piece-quarter-eyes',
  '@generative-music/piece-return-to-form',
  '@generative-music/piece-sevenths',
  '@generative-music/piece-spring-again',
  '@generative-music/piece-timbral-oscillations',
  '@generative-music/piece-townsend',
  '@generative-music/piece-trees',
];
